### ISSUE TITLE
Feature Request: Liferay Portal CE 7.3.x Without Commerce Module

### ISSUE THREAD

**Issue by netlander** [igor-baiborodine/docker-liferay-portal-ce#3]
Is there a possibility to adapt one of these Docker images with the removal of the Commerce bloat that was added to 7.3.x?

**Comment by igor-baiborodine** [comment]
@netlander, let me check if it can be done.

**Comment by netlander** [comment]
@igor-baiborodine, good to see that 7.2.x (which I'm currently using from stock Liferay images) has no such bloat and I've also noticed this repo contains a couple of images supporting that version.

So I was wondering if these 7.2 images have been used in production and whether they are as "reliable" as the stock Liferay Docker images?

**Comment by igor-baiborodine** [comment]
@netlander 
RE: _So I was wondering if these 7.2 images have been used in production and whether they are as "reliable" as the stock Liferay Docker images?_
I personally didn't use these images in production. These images are based on the same Liferay/Tomcat bundle(which comes from https://releases.liferay.com/portal) as the stock Liferay images. 

RE: _Is there a possibility to adapt one of these Docker images with the removal of the Commerce bloat that was added to 7.3.x?_
It is possible to strip the bundle of anything related to the Commerce suite, but since Liferay Inc. decided to bundle it together with the Liferay Portal CE, images will stay as is.
![image](https://user-images.githubusercontent.com/1027701/98539177-e6876a00-2259-11eb-8fb5-0799489028bf.png)
